[default]
    SQLALCHEMY_DATABASE_URI='mysql+pymysql://root:senhadb@localhost/test'
    TITLE = "Mercadinho"

    EXTENSIONS = [
        "mercadinho_do_ze.extensions.appearance",
        "mercadinho_do_ze.extensions.database",
        "mercadinho_do_ze.extensions.auth",
        "mercadinho_do_ze.blueprints.webui",
        "mercadinho_do_ze.blueprints.restapi"
    ]
